#  require 'rails_helper'
#
# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to test the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator. If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails. There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# RSpec.describe "/configurations", type: :request do
#
#   # Configuration. As you add validations to Configuration, be sure to
#   # adjust the attributes here as well.
#   let(:valid_attributes) {
#     skip("Add a hash of attributes valid for your model")
#   }
#
#   let(:invalid_attributes) {
#     skip("Add a hash of attributes invalid for your model")
#   }
#
#   describe "GET /index" do
#     it "renders a successful response" do
#       Configuration.create! valid_attributes
#       get configurations_url
#       expect(response).to be_successful
#     end
#   end
#
#   describe "GET /show" do
#     it "renders a successful response" do
#       configuration = Configuration.create! valid_attributes
#       get configuration_url(configuration)
#       expect(response).to be_successful
#     end
#   end
#
#   describe "GET /new" do
#     it "renders a successful response" do
#       get new_configuration_url
#       expect(response).to be_successful
#     end
#   end
#
#   describe "GET /edit" do
#     it "render a successful response" do
#       configuration = Configuration.create! valid_attributes
#       get edit_configuration_url(configuration)
#       expect(response).to be_successful
#     end
#   end
#
#   describe "POST /create" do
#     context "with valid parameters" do
#       it "creates a new Configuration" do
#         expect {
#           post configurations_url, params: { configuration: valid_attributes }
#         }.to change(Configuration, :count).by(1)
#       end
#
#       it "redirects to the created configuration" do
#         post configurations_url, params: { configuration: valid_attributes }
#         expect(response).to redirect_to(configuration_url(Configuration.last))
#       end
#     end
#
#     context "with invalid parameters" do
#       it "does not create a new Configuration" do
#         expect {
#           post configurations_url, params: { configuration: invalid_attributes }
#         }.to change(Configuration, :count).by(0)
#       end
#
#       it "renders a successful response (i.e. to display the 'new' template)" do
#         post configurations_url, params: { configuration: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end
#
#   describe "PATCH /update" do
#     context "with valid parameters" do
#       let(:new_attributes) {
#         skip("Add a hash of attributes valid for your model")
#       }
#
#       it "updates the requested configuration" do
#         configuration = Configuration.create! valid_attributes
#         patch configuration_url(configuration), params: { configuration: new_attributes }
#         configuration.reload
#         skip("Add assertions for updated state")
#       end
#
#       it "redirects to the configuration" do
#         configuration = Configuration.create! valid_attributes
#         patch configuration_url(configuration), params: { configuration: new_attributes }
#         configuration.reload
#         expect(response).to redirect_to(configuration_url(configuration))
#       end
#     end
#
#     context "with invalid parameters" do
#       it "renders a successful response (i.e. to display the 'edit' template)" do
#         configuration = Configuration.create! valid_attributes
#         patch configuration_url(configuration), params: { configuration: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end
#
#   describe "DELETE /destroy" do
#     it "destroys the requested configuration" do
#       configuration = Configuration.create! valid_attributes
#       expect {
#         delete configuration_url(configuration)
#       }.to change(Configuration, :count).by(-1)
#     end
#
#     it "redirects to the configurations list" do
#       configuration = Configuration.create! valid_attributes
#       delete configuration_url(configuration)
#       expect(response).to redirect_to(configurations_url)
#     end
#   end
# end
