# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "connector_backend_example"
  group_id_prefix: 'connector_backend_example' #Ryan's todo: need to verify.

development:
  <<: *common
  brokers:
    - <%= Settings.kafka-broker-1 || "localhost:9092" %>

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  brokers:
    - <%= Settings.kafka_broker_1 %>
    - <%= Settings.kafka_broker_2 %>

sandbox:
  <<: *common
  brokers:
    - <%= Settings.kafka_broker_1 %>
    - <%= Settings.kafka_broker_2 %>